[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
inc = "oerHQbgnZu3h3inupfhAYgL6V9KbW1XSdKsvD1Ch8ox"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ankit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
